version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: gestion_extrait_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: gestion_extrait
      MYSQL_USER: extrait_user
      MYSQL_PASSWORD: extrait1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: